title: "Full Trottel Racing"
description: "Motorcycle racing team — News, trackdays and build reports"
logo: "/assets/images/logo.png"
baseurl: ""
u: "https://antonsperling.github.io"
theme: minima
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
